# Generated by Django 4.2.6 on 2023-11-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_order_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Not out yet'), (2, 'On the way'), (3, 'Delivered')], default=1, verbose_name='Delivery status'),
        ),
    ]
